### ISSUE TITLE
Feature Request: Camera needs to provide an image

### ISSUE THREAD

**Issue by JurajNyiri** [JurajNyiri/HomeAssistant-Tapo-Control#17]
**Is your feature request related to a problem? Please describe.**
Camera is currently not able to provide an image, only video streams.

**Describe the solution you'd like**
Camera should be able to provide an image from the current stream, ideally without processing on the HASS side.

**Describe alternatives you've considered**
We could get the image from the stream on the hass, but in order to save resources we should find a way to get it directly from the camera.

**Additional context**
I need help with finding the API call for an image. If someone knows how to do this please let me know.
I might be able to mitm reverse engineer the camera but I was not successful yet.

**Comment by JurajNyiri** [comment]
Done in future release 2.1.

**Comment by v1nc** [comment]
How can I access the camera image?
I tried to create a snapshot with `camera.snapshot`, but it only creates an empty file.

**Comment by JurajNyiri** [comment]
You can use for example https://www.home-assistant.io/lovelace/picture-entity/

Snapshot has not been tested / implemented yet.

**Comment by v1nc** [comment]
I still don't get how to display a static image. If I add a picture entity and configure the camera entity, it shows the live stream. Didn't this worked before the update?

**Comment by JurajNyiri** [comment]
It works like any other camera on home assistant. Previously, there was no image.
