### ISSUE TITLE
Bug: C310 Motion sensor stops working or becomes unavailable

### ISSUE THREAD

**Issue by dankocrnkovic** [JurajNyiri/HomeAssistant-Tapo-Control#84]
**Describe the bug**
Motion sensor stops reporting state change after some time. (daily).
Stream still works.
Sometimes motion sensor in HA reports unavailabe and somtimes it just stays in off state.
Motion is still detected on camera and recordings work on Android Tapo app.

Reseting motion detection on camera or rebooting camera does not help. Only HA restart recovers motion detection state change.

I have explicitly opened ports on firewall 2020,554,443,1024 but result is the same. 

**Log**
No log entries. 
```

**Camera (please complete the following information):**
C310

**Using stream component**
Yes

**Camera works through onvif component OR different cameras work in general**
Camera and motion detection works in Android Tapo app.

**Camera has all attributes filled out properly in developer tools**
yes

**HASS Environment**
Supervised HA OS (RP 4)

**Comment by JurajNyiri** [comment]
Hello @dankocrnkovic 

I have pushed a version with debug logs into main branch. Please download that manually (not available on HACS) and configure [logger](https://www.home-assistant.io/integrations/logger/) to log debug for this component.

```
logger:
  default: critical
  logs:
    custom_components.tapo_control: debug
```

On a first successful motion detection you should see a message "Found event which doesn't have entity yet, adding binary sensor!".

When it happens the next time, please restart the camera without restarting home assistant and post all the logs here.

**Comment by dankocrnkovic** [comment]
Hell @JurajNyiri Is this change included in new release: 3.3.1w ?

danko

**Comment by JurajNyiri** [comment]
Hello yes it is.

**Comment by dankocrnkovic** [comment]
@JurajNyiri 
Yesterday just about after finishing posting this issue, there was a firmware update for C310 camera in Tapo App. 
Its been 24 hours that I didnt restart HA (I had to later today to update and enable logging). In this 24 hour sensor was working. Usually I would have this problem twice a day.
So maybe firmware fixed something. I will monitor this and report.

But, I'm confused now as you stated with latest update that new firmware version is  1.1.7, but my version from yesterday is 1.0.14 Build 210118 Rel.58915n(4555)

**Comment by JurajNyiri** [comment]
Maybe they have different versions for C310.

For motion sensor onvif event manager from home assistant is used, which is keeping itself alive during camera restarts, connection loss etc, so most likely change will be needed on Home Assistant side.

Before that we need to determine the cause though that's why I added the debugging. 

There might be a way how to work around it until it is fixed or it might be something I missed. Either way we will find out when it happens again.

**Comment by dankocrnkovic** [comment]
[home-assistant.zip](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/6365456/home-assistant.zip)
Here it is. It happend. 
I noticed around 14:45.
Rebooted camera and nothing changed. I noticed in log that it reports everything is ok.
But, motion is not detected. In Tapo App motion is detected and all i ok.

Its a big log. 

d.

**Comment by dankocrnkovic** [comment]
I waited till now (5 hours) and nothing new happened. So I restarted HA.
After restart sensor was unavailable until first motion detected and now sensor is reporting ok.
I attached new log that shows this.
[home-assistant.log](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/6367136/home-assistant.log)

**Comment by JurajNyiri** [comment]
That confirms my belief that the Home Assistant event manager is not able to recover properly.

```
logger:
  default: critical
  logs:
    custom_components.tapo_control: debug
    homeassistant.components.onvif: debug
```

Lets add debug for it and observe how it behaves when it stops working.

This is an example of successful recovery on camera reboot:

```
2021-04-23 21:40:15 WARNING (MainThread) [homeassistant.components.onvif] Failed to fetch ONVIF PullPoint subscription messages for '28f39a982d2634f6aa21be4917158645_tapo_events': [Errno 61] Connect call failed ('192.168.100.70', 1025)
2021-04-23 21:40:19 DEBUG (MainThread) [custom_components.tapo_control] Finished fetching Tapo resource status data in 68.889 seconds
2021-04-23 21:40:20 DEBUG (MainThread) [homeassistant.components.onvif] Restarted ONVIF PullPoint subscription for '28f39a982d2634f6aa21be4917158645_tapo_events'
2021-04-23 21:40:29 DEBUG (MainThread) [custom_components.tapo_control] async_update_data - entry
```

Lets see what does it do when it stops receiving events. Once we have that information we can move forward and create a bug report on Home Assistant and/on workaround it via integration somehow.

**Comment by dankocrnkovic** [comment]
Are you sure that log category is homeassistant.components.onvif?

This is from my configuration.yaml:
logger:
  default: warning
  logs:
    custom_components.tapo_control: debug
    homeassistant.components.onvif: debug

There is no log record after HA restart, camera reboot, tapo app motion detection, and now I noticed that sensor is not working again. No log.

**Comment by JurajNyiri** [comment]
Hello yes I tested it before sending. Try to add it, make motion so that sensor shows up and reboot camera, you should get log from onvif.

**Comment by Akkor70** [comment]
Hi
I have the samme Issue
I added the logs option to configuration.yaml , rebooted HA and cameras
It seems to me that the motion sensor is unavailable since the cam detect a movement.....then the sensor became available, but after some time is unavailable again (some idle time ?)
I have a log https://pastebin.com/mdTcBs1p

**Comment by JurajNyiri** [comment]
Did you add log also for onvif? I can't see anything from it in the logs and there should be something there where it attempts to recover.

1. Add logs for tapo and onvif as described above
2. Restart hass
3. Make a motion so that sensor shows up
4. Reboot camera via service
5. Make a motion so that sensor shows up
6. Keep camera with privacy mode off, basically don't change anything on the camera since point 4
7. When it stops detecting motion correctly, post all the logs

**Comment by Akkor70** [comment]
> Did you add log also for onvif? I can't see anything from it in the logs and there should be something there where it attempts to recover.
> 
> 1. Add logs for tapo and onvif as described above
> 2. Restart hass
> 3. Make a motion so that sensor shows up
> 4. Reboot camera via service (once camera is up, and or when motion is detected again, there should be a log from onvif, you can verify that here)
> 5. Make a motion so that sensor shows up
> 6. Keep camera with privacy mode off, basically don't change anything on the camera since point 4
> 7. When it stops detecting motion correctly, post all the logs

I made all steps as descrbed, the only mismatch is that I rebboted the cam from Tapo App
I'll wait the movement sensor stop working to post the log again........

**Comment by JurajNyiri** [comment]
Please verify that the log for onvif is working. Without it waiting for logs from tapo brings no new information.

**Comment by Akkor70** [comment]
> Please verify that the log for onvif is working. Without it waiting for logs from tapo brings no new information.

This is my config

```
logger:
  default: critical
  logs:
    homeassistant.components.automations: debug
    custom_components.tapo_control: debug
    homeassistant.components.onvif: debug
```

**Comment by JurajNyiri** [comment]
1. Add logs for tapo and onvif as described above
Restart hass
2. Make a motion so that sensor shows up
3. Reboot camera via service (**once camera is up, and or when motion is detected again, there should be a log from onvif, you can verify that here)**
4. Make a motion so that sensor shows up
5. Keep camera with privacy mode off, basically don't change anything on the camera since point 4
6. When it stops detecting motion correctly, post all the logs

**Comment by Akkor70** [comment]
> 1. Add logs for tapo and onvif as described above
> 2. Restart hass
> 3. Make a motion so that sensor shows up
> 4. Reboot camera via service (**once camera is up, and or when motion is detected again, there should be a log from onvif, you can verify that here**)
> 5. Make a motion so that sensor shows up
> 6. Keep camera with privacy mode off, basically don't change anything on the camera since point 4
> 7. When it stops detecting motion correctly, post all the logs

Onvif log is working becouse when I restart the camera from service I got this

```
2021-04-24 22:06:02 ERROR (stream_worker) [libav.tcp] Connection to tcp://192.168.1.61:554?timeout=5000000 failed: Operation timed out
2021-04-24 22:06:04 ERROR (stream_worker) [libav.tcp] Connection to tcp://192.168.1.85:554?timeout=5000000 failed: Operation timed out
2021-04-24 22:06:13 WARNING (MainThread) [homeassistant.components.onvif] Failed to fetch ONVIF PullPoint subscription messages for 'f2b5148ba1da55a033b8c575a149f9a3_tapo_events':
2021-04-24 22:06:19 ERROR (MainThread) [custom_components.tapo_control] HTTPSConnectionPool(host='192.168.1.85', port=443): Max retries exceeded with url: /stok=4d1a9607399fb6d9094cb3198f9d1ede/ds (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f25e342af40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2021-04-24 22:06:19 DEBUG (MainThread) [custom_components.tapo_control] Finished fetching Tapo resource status data in 31.489 seconds
2021-04-24 22:06:19 ERROR (stream_worker) [libav.tcp] Connection to tcp://192.168.1.85:554?timeout=5000000 failed: Connection refused
2021-04-24 22:06:20 WARNING (MainThread) [homeassistant.components.onvif] Failed to fetch ONVIF PullPoint subscription messages for '5a7801df5d943ccdbf8adc8dea0cc7c0_tapo_events':
2021-04-24 22:06:20 WARNING (MainThread) [homeassistant.components.onvif] Failed to restart ONVIF PullPoint subscription for '5a7801df5d943ccdbf8adc8dea0cc7c0_tapo_events'. Retrying
2021-04-24 22:06:21 WARNING (MainThread) [homeassistant.components.onvif] Failed to restart ONVIF PullPoint subscription for 'f2b5148ba1da55a033b8c575a149f9a3_tapo_events'. Retrying
```
Now I'll wait the sensor stop working to post log

**Comment by JurajNyiri** [comment]
I was able to replicate this, by disconnecting HOST from network.

Home Assistant onvif event manager is no longer able to reconnect.

```
2021-04-24 23:00:06 WARNING (MainThread) [homeassistant.components.onvif] Failed to restart ONVIF PullPoint subscription for 'c38ba820a0eddb08cda53d5bea952b9e_tapo_events'. Retrying
``` 

on repeat.

Figuring out next steps...

**Comment by JurajNyiri** [comment]
So after investigating, I have found out that it doesn't seem to be the same case. 
1. Disconnected HASS host
2. Reconnected HASS host after a minute
3. Onvif was failing to recover as described above
4. Rebooted camera
5. Onvif recovered

Download and rename [event.txt](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/files/6370717/event.txt) into event.py and place into your pip3 libraries folder, into like site-packages/homeassistant/components/onvif/event.py .

It is the same event.py as provided by Home Assistant, but with a ton more debug messages I added.

The next time it happens on its own after some time, please note an approximate time of when it happened.
After that, reboot the camera, note time.
Try to make a ton of motion etc etc, so that it has a possibility to recover, leave it be for 5 min, do a ton of motion again.
If not still recovered, please post logs. @Akkor70 @dankocrnkovic

**Comment by dankocrnkovic** [comment]
I simply can not get onvif logs :(
Rebooted camera via service and nothing new in log.

@Akkor70  did you manage to go forward with debugging?

d.

**Comment by Akkor70** [comment]
> I simply can not get onvif logs :(
> Rebooted camera via service and nothing new in log.
> 
> @Akkor70 did you manage to go forward with debugging?
> 
> d.

I'm waiting for motion sensor stop working

**Comment by dankocrnkovic** [comment]
As I cant get logs to work, Motion stop reporting today and I just restarted HA without rebooting camera. And it recovered after HA restart. So, its not in camera problem as it seams.

d.

**Comment by JurajNyiri** [comment]
@dankocrnkovic its a Home Assistant issue (99% probably not this integration), we just need to narrow it down and then workaround it and/or create an issue/fix for Home Assistant.

**Comment by JurajNyiri** [comment]
Hey @Akkor70 any updates with the logs?

**Comment by Akkor70** [comment]
No man
I'm in trouble with HA atm
I'll post asap

**Comment by monotonus** [comment]
Seems to be the same issue with my C200 with newest firmware and newest Tapo integration

**Comment by JurajNyiri** [comment]
@monotonus we need logs i described above to proceed with this as i cannot replicate it

**Comment by dankocrnkovic** [comment]
@JurajNyiri 
Just to report... In the last month, I did not had any problems.  Maybe something changed in HA core.

**Comment by JurajNyiri** [comment]
@dankocrnkovic that is possible as integration is using onvif provided by hass.. Also there were a couple of updates to firmware which might have helped. Let's keep this open for a few more weeks to see if anyone is still facing issues.

**Comment by raihatneloy** [comment]
Hi, I am using C200 and facing the same issue. The sensor stops reporting motion sometimes. Like - currently I am seeing it is not reporting motion for last 3 hours. But the app is notifying me perfectly. At that moment, if I restart HASS, the sensor becomes unavailable and then I have to delete and re-add the camera. I am also unable to debug the logs, not coming! Using HASS core of version 2021.06.05. I am using the camera as baby monitor, so this motion sensor is really important one :(

**Comment by JurajNyiri** [comment]
> Hi, I am using C200 and facing the same issue. The sensor stops reporting motion sometimes. Like - currently I am seeing it is not reporting motion for last 3 hours. But the app is notifying me perfectly. At that moment, if I restart HASS, the sensor becomes unavailable and then I have to delete and re-add the camera. I am also unable to debug the logs, not coming! Using HASS core of version 2021.06.05. I am using the camera as baby monitor, so this motion sensor is really important one :(

Hello, unfortunately without logs we cannot move forward. The issue you have described is s different one to what is described here - restarting hass helps. It also doesnt make much sense. Readding camera and resetting hass does the same things from camera point of view.

**Comment by CoYoNq** [comment]
Motion sensors with TAPO APP running in any device in the network (ie in an android device, where app runs in background), makes sensor detection fail times to times. Kill the app in your device (stop it) and sensors gonna show again.
Looks like low profile cams (like tapo C100) can report only once, and TAPO app monopolices it.
C320 uses not to fail, ie.
Bassically, it is not a bug (in the project). Its a limitation of some hardware (or a bug in firmware)
Hope my research helps.

**Comment by bolderiz** [comment]
> I'm haveing a C200 with HomeAssistant 2021.9.7 aswell as an instance with 2021.10.0. Installation of the integration works so far. The motion detection sensor is also working but after ~24hrs the sensor is in state unavailable. I checked everything according to the FAQ but it does not help. The FW of the cam is 1.1.11

Me too. I activated logger. I don't see any info of onvif component

**Comment by paqp** [comment]
hi! after last firmware my tapo c310 (3 in total) are crashing every day twice a day.
I thought it was due to tapo app opened. But they are now under firewall and cannot talk with internet. Same problem.
Every camera reboot itself at night.

**Comment by liakjim** [comment]
Hello, user with a tapo c200. Sometimes this issue happens to me. It is always solved by a ha restart.

**Comment by JurajNyiri** [comment]
Responding me too does not help resolving this issue. Please see detailed instructions on what information to provide in my last comments.

**Comment by paqpal** [comment]
> Responding me too does not help resolving this issue. Please see detailed instructions on what information to provide in my last comments.

Did my log help you? I'm not a le to handle python... I see that as much as I update HA, problem presents frequently, now 3 times a day with tapo c310 gen 1, 1 time with tapo v2.

**Comment by JurajNyiri** [comment]
> > Responding me too does not help resolving this issue. Please see detailed instructions on what information to provide in my last comments.
> 
> Did my log help you? I'm not a le to handle python... I see that as much as I update HA, problem presents frequently, now 3 times a day with tapo c310 gen 1, 1 time with tapo v2.

No, that log seems to be unrelated to this issue as this is not about camera being unresponsive, but about its motion sensor stopping changing state.

**Comment by rkkoszewski** [comment]
I'm having the same issue with a Tapo C110. In my case restarting HA does not solve the issue. It actually shows up after restarting HA. Maybe it stops working earlier, but the sensor shows as "Clear" and after HA restart it shows as "Unavailable". Any further restarts of HA (Even full OS reboot) have no effect and do not fix the issue. Disabling "Enable motion sensor" and then enabling it again seems to make the motion sensor work again (No HA restart necessary). I'll try to play with the integration's Debug options and how OVNIF is working here (Smells to me like a subscription to the motion event expires and is never refreshed, but I haven't yet looked how the integration works). I'll report back.

**Comment by barisozdag** [comment]
I was having this problem too. But I haven't encountered any "Unavailable" status for 2 days.

I have Tapo C200. My situation was different from what is written here. Previously, it was in the "Unavailable" state, but when motion was detected in front of the camera, it went into the "detected" state. After staying in the "Clear" state for a while when there was no movement, it would occasionally switch to the "unavailable" state. I've never had to restart the home assistant. So unfortunately I didn't get any debug logs.

Two days ago I both upgraded Home assistant to version 2021.11.5 and used "binary_sensor.c200_motion" as a trigger in an automation. When I look in History there are no "Unavailable" statuses since then.
![image](https://user-images.githubusercontent.com/596414/143219384-37c26ca1-83f3-4937-beb2-962f091d1aff.png)

**Comment by d99pli** [comment]
Having the same issue with both C200, C310 and C320:s becoming unavailable every now and then, have not been able to identify root cause. Motion detection with the Tapo app works without issues, it is the Onvif cell_motion_detection sensor that becomes unavailable. Sometimes a HA reboot solves the problem, but not always, very confusing behaviour. Happy to help with submitting logs.

**Comment by vsimanin** [comment]
I have the same problem for the last month.  Cameras C100 and C200.  Approximately 1 time at 21-30 hours the motion sensor stops registering events.  Rebooting HA helps.  Please check my version, but this seems to happen when the wi-fi connection is disconnected.  I tried turning the router off and on.  The sensor stopped registering events.
![Uploading Screenshot_20220912-153944.jpg…]()

**Comment by baradetsky** [comment]
+1 the same issue with C100 (but C210 works properly) 
![2022-11-13_11-17-53](https://user-images.githubusercontent.com/96811123/201505468-0c958a60-f7d0-4c51-b093-5f22a239ce51.png)

**Comment by vsimanin** [comment]
> I have the same problem for the last month.

I stopped getting this error a very long time ago. I think I understood what it was connected with in my case. The router periodically gave the IP address of the camera to another device, but it remains fixed in the smart home integration. Registered the address static. The problem has not occurred for several months.

**Comment by pietronicoletti** [comment]
I have the same problem from yesterday with C210, HA tells me that the integration doesn't support the entity ".binary_sensor.tapo_camera_motion..."

**Comment by fballiano** [comment]
same to me, with my C110 I get an error that the entity is no longer provided by integration tapo_control

**Comment by CoYoNq** [comment]
As long as i was testing, this issue uses to show up when network 
latency increases too much.

In my setup (raspberry pi4+ with one C100 direct via integrated wireless 
and one C100 and a C310 vía my wireless router), the ones via the 
router, when lan gets loaded (making ping increases), uses to disable 
the sensor service.

Maybe the original firmware has some kind of check and disables the 
"sensor" channel due to this lack of good response times (this motion 
sensor is a software one, comparing images only, and a high latency 
makes it useless)

IMHO this issue comes from this situation. Try to improve network, to 
help to check this theory? Tapo python libs do any kind of check of this 
situation?

**Comment by Sergi0Martin** [comment]
Same error here and solved temporaly disableing and enableing motion sensor.

![image](https://user-images.githubusercontent.com/16337833/210519030-586e86df-541e-49ad-86b5-698e934685c4.png)

**Comment by fballiano** [comment]
The motion sensor never works, I'm thinking I have to switch to another camera because here we have a problem.

**Comment by CoYoNq** [comment]
First of all, test it on tapo original app if you think motion detection 
is not working (but, FYI, motion detection is made by software, so, if 
the cam works and show image, for sure motion is detected)

Adjust it (area, sens) within the app.

For sure you gonna get it woking.

**Comment by fballiano** [comment]
it works in the TAPO app but not in HA, it tells "this device is no longer provided by the tapo integration" (or something along these lines) or anyway it become unavailable and stops working (in HA).

**Comment by JurajNyiri** [comment]
All these comments are not helping to find the solution. Most of the time the issue is with users network and stability.
If there is an error with this integration, follow the steps I posted [above](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/84#issuecomment-826156024), if you do not, your comment does not help in any way.

**Comment by CoYoNq** [comment]
Let me share some of my experiences with this device.

Motion sensor uses to dissapear in some cases:

1 - bad network connection: high network latency ie. makes sensor to 
dissapear in some cases. To solve, check the cam and AP location (if 
wireless) and do a ping test.

2 - other app in use with the cam (like the tapo app). Kill the app in 
your device to prevent it running in backgroud. This devices uses 
software detections, and looks like creating multiple sockets 
complicates the functionality.

3 - remove cam from integration and re-add it. So, device is re 
consulted about their capacities and report correctly the motion 
detection sensor. (in the first start, the sensor uses not to be 
reported as active or valid, but at first motion detected, it uses to 
appears normally.

Hope this tips helps.

**Comment by andree182** [comment]
To try to debug this issue, I am currently running this Tapo Control in parallel with the ONVIF component. In addition, it seems to me that restarting HA (and thus connection to the Tapo devices) helps, while restarting the devices doesn't seem to (curious, right?).

![image](https://user-images.githubusercontent.com/1175689/214523587-14f61a3d-19b7-4902-86a1-1a859ba478a6.png)

In the picture above, the top 2 rows is the TapoControl  (motion and motion2), while the bottom two are from ONVIF. For whatever reason, I rarely see the "motion" sensor available for TC, and it seems always 'off' for ONVIF. The interesting part is the difference in the detected activity on the first camera... But as evident, sometimes ONVIF catches, sometimes TC, sometimes both.

Also, in the picture @ 1:00 , HA was restarted.

So I'll be watching it for the coming few days, in the meantime I'm using both motion2 sources as triggers I guess.

**Comment by JurajNyiri** [comment]
Closing due to inactivity.
