### ISSUE TITLE
Tapo C320WS new spotlight intensity number shows incorrect range

### ISSUE THREAD

**Issue by Spamfast** [JurajNyiri/HomeAssistant-Tapo-Control#889]
### Description

I noticed that recently the select entity for spotlight intensity for my C320WS has been replaced with a number entity. This incorrectly has a max attribute of 100 when it should be 5. 

On my C210 & C110 cameras the spotlight intensity is still a select with options 1 to 5.

### Reproduction Steps

Update to latest firmware & latest integration version.

### Expected behavior

Entity should either be a select with options 1 to 5 or a number with min/max 1/5 attributes.

### Device Firmware

1.4.1 Build 250106 Rel.44456n

### Integration Version

6.1.3

### Using stream component

Yes

### Does camera work via official integrations?

Yes

### Camera has all attributes filled out in developer tools

Yes

### HASS Environment

Bare-metal HA OS

### Search for similar issues

Yes

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/6.1.6

**Comment by Spamfast** [comment]
Since I raised the issue I've purchased a Tapo C211 that also exhibited the same problem with 6.1.5. After upgrading to 6.1.6 the spotlight intensity 'max' attribute on the C211 is now correctly set to 5 but the one for the C320WS is still showing 100. Let me know if/how I can provide diagnostic dumps that might help.

**Comment by JurajNyiri** [comment]
Please enable debug logs and send here 1 minute after integration launch.

**Comment by Spamfast** [comment]
[home-assistant.log](https://github.com/user-attachments/files/20595404/home-assistant.log)

I enabled debug logging for the camera integration then restarted HA.

Note that I've renamed 'Spotlight' to 'Floodlight' in entity friendly names and also 'spotlight' to 'floodlight' in entity IDs.

The C211 camera is called 'Odin' (number.odin_floodlight_intensity) and the C320WS is 'Steropes' (number.steropes_floodlight_intensity).

Hope that helps.

**Comment by Spamfast** [comment]
Oops. That log file had some sensitive information in it. I'll repost after sanitizing...

**Comment by Spamfast** [comment]
[home-assistant.log](https://github.com/user-attachments/files/20595748/home-assistant.log)

Okay. New log copied after enabling Tapo Camera integration debug logging and restarting HA.

For the cameras in question I've renamed all 'Spotlight' to 'Floodlight' in friendly names and 'spotlight' to 'floodlight' in entity IDs.

The C211 camera is called 'Odin' (number.odin_floodlight_intensity) and the C320WS is 'Steropes' 'number.steropes_floodlight_intensity).

Hope this helps.

**Comment by Spamfast** [comment]
Oh, to home in on the relevant cameras, the C211 Odin has IP address 192.168.27.21 and the C320WS Steropes has address 192.168.26.73.

**Comment by JurajNyiri** [comment]
Thank you, this confirms the assumption that if camera contains `white_lamp` under getNightVisionCapability it has a range of 100 is incorrect. I will need to find another differentiating factor but with the current data there doesn't seem to be one. A new call will need to be discovered that returns the range.

For now as a workaround until this gets fixed you can create a new select or number helper entity and automate a change on that to trigger a change on this number entity.

**Comment by Spamfast** [comment]
Thanks for looking. My current workaround is homeassitant:customize:number.steropes_floodlight_intensity:max: 5 which fixes the problem for that camera.

**Comment by Spamfast** [comment]
Well, I suppose you could special-case for ['getDeviceInfo'][0]['device_info']['basic_info']['device_model'] == 'C320WS' but it's not a quality solution.

An overide table keyed on device_model with entries that can override those determined generically from other keys might be a more maintainable solution but it's also a bit kludgy.

Hey ho. Not exactly urgent given how easy the workaround is.

Thanks for the fix that works for C211 and for the whole integration of course. :-)

**Comment by JurajNyiri** [comment]
@Spamfast could you please test https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/tree/v6.1.7 ?


After significant research I was not able to find any related additional call that app could use to differentiate between max ranges. So I took another look into what is different between one of my cameras (C520WS) with 100, C200 with 5 and your cameras and I believe I found it.

**Comment by Spamfast** [comment]
Hi. I'm not familiar enough with HACS to tell it to use a non-released tag. Can you give me as hint, please?

**Comment by JurajNyiri** [comment]
Install manually https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/tree/v6.1.7?tab=readme-ov-file#installation. [Download it as a zip](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/archive/refs/heads/v6.1.7.zip), and replace in your HA, then restart HA.

**Comment by Spamfast** [comment]
Right.
Removed my customization, replaced the contents of custom_components/tapo_control with the ZIP folder and restarted.

Both Odin & Steropes now both have max: 5.

Job done, I think. :-)

**Comment by JurajNyiri** [comment]
Fixed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/6.1.7 .
